# Generated by Django 5.2 on 2025-09-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(max_length=700)),
                ('solutions', models.CharField(max_length=700)),
                ('why_it_works', models.CharField(max_length=700)),
                ('benifits', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.CharField(max_length=400)),
                ('operational', models.CharField(max_length=400)),
                ('team', models.CharField(max_length=400)),
                ('expected_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea_images', models.ImageField(blank=True, null=True, upload_to='idea_photos/')),
                ('categories', models.ManyToManyField(related_name='categories', to='preferences.preferences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
                ('description', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.ideadescription')),
                ('requirements', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.idearequirement')),
            ],
        ),
    ]
