# Generated by Django 5.2 on 2025-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0002_preferences_type_alter_preferences_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('problems', models.CharField(max_length=400)),
                ('solutions', models.CharField(max_length=400)),
                ('why_it_works', models.CharField(max_length=700)),
                ('benifits', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='preferences.preferences')),
            ],
        ),
    ]
