# Generated by Django 5.2 on 2025-05-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tabs_order',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='TabContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('description', 'Description'), ('requirements', 'Requirements'), ('about', 'About'), ('team', 'Team')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='ideas.idea')),
            ],
        ),
    ]
