# Generated by Django 5.2 on 2025-05-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_remove_idea_image_remove_idea_tabs_order_ideaimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideaimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='ideaimage',
            name='order',
        ),
    ]
