# Generated by Django 5.2 on 2025-05-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_idea_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdeaImage',
        ),
    ]
