# Generated by Django 5.2 on 2025-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Creative', 'creative'), ('Investor', 'investor')], max_length=10),
        ),
    ]
