# Generated by Django 5.2 on 2025-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_profile_user_type_passwordrestcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrestcode',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
