# Generated by Django 5.2 on 2025-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_profile_bio_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
