# Generated by Django 5.2 on 2025-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('filter', 'Filter'), ('location', 'Location')], default='category', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferences',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
